dataset: "LJSpeech"

path:
  corpus_path: "./data/angelina"
  lexicon_path: "lexicon/new_spanish.txt"
  raw_path: "./raw_data/angelina"
  preprocessed_path: "./preprocessed_data/angelina_aligned"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
    use_lexicon: True
    use_cmudict: False
  audio:
    sampling_rate: 16000
    max_wav_value: 32767.0
  stft:
    filter_length: 743
    hop_length: 186
    win_length: 743
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
